Due Oct. 21 at 11:59 PM.

For this first part of the exam, you can either use surveys_complete.csv or your own data. If you are using your own data, you must have data in which you think you have a numerical predictor variable and a numerical response variable. If you are using surveys_complete, you can use weight and hindfoot_length for this.

Save this file in your projects directory. You can either save it in a project two subdirectory, or just put it in projects. Either way is fine.

Load in your data. Which variable will you be using as a predictor, and which as a response? (5 pts)
# Predictor =  Segregating.Sites  Response = Tajima.Pi
# Answer which column is predictor and which is response

Plot the two against each other with a scatter plot. Do the data appear to be related linearly? (5 pts)
> ggplot(Dataclean, aes(x = Segregating.Sites, y = Tajima.Pi)) + 
+     geom_point() + geom_jitter()
# Yes they do appear the be related linearly

Fit the linear model. View the summary. (5 pts)
>summary(Datalma)

Does the summary make sense when you compare it to the plot you made? Does our model have good predictive power? Evaluate the residual standard error, intercept, and R-Squared in particular. Would you say your predictor predicts the response? (10 pts)
# I belive that when i compared the summary to the plot it came out pretty accurate and shows the model has a good predictive power. I feel that it predicted the standard error, intercept, and R-Squared correctly.

Plot the model on the graph. Increase the size of the text so it is comfortably readable at 5 feet. Make sure axis labels are readable and not overlapping with one another. (5 pts)
> ggplot(Dataclean, aes(x = Segregating.Sites, y = Tajima.Pi)) +
+      geom_point() +
+      geom_smooth(method = "lm",
+                               color = "red",
+                               fill = "deeppink4") +
+      annotate("text",
+               x = .3, y = 3,
+                         label = "R^2 == 0.999",
+                         parse = T)

Check the normality of the residuals. Do they look OK? Are we violating assumptions? (5 pts)
> qqnorm(broomdata$.resid)
> qqline(broomdata$.resid, col = "blue")
It looks ok and we are not violating assumptions.

Why is normality of residuals important?

# normality of residuals are important because it shows if the model is right.

If you are using surveys_complete: Is there interspecific variation in the linear model? Hint: look at our prior work with facet plots. (15 pts)

If you are not using surveys_complete: Do you think there are groupings within your data that may have a separate linear model? Try grouping the data by that variable and redoing the lm. If this would not make sense for your data, you may also attempt to do multiple predictor variables. (15 pts)
> second_fit <- lm(Theta ~ Tajima.D, data = Dataclean)
Yes there is another one that will give a linear model

Part Two
In this portion, you are free to use your own data if you have a categorical predictor variable and a response variable. Otherwise, you may use the columns sex and weight in surveys_complete

First, plot the data grouped by sex (5 pts)
> ggplot(Dataclean, aes(x = Theta, y = Tajima.D)) + geom_point()

Try an ANOVA of this data (5 pt)
> second_fit <- lm(Theta ~ Tajima.D, data = Dataclean)
> summary(second_fit)

How about a linear model? What information does this give you that an ANOVA can’t? (5 pts)
ggplot(Dataclean, aes(x = Theta, y = Tajima.D)) + geom_point() + geom_jitter()

# The model gives me a visual view of the information.

Plot the lm with the data, with points colored by sex. (10 pts)
> ggplot(Dataclean, aes(x = Theta, y = Tajima.D, color = Segregating.Sites)) + geom_point() + geom_jitter()

Choose any model we’ve looked at so far, but use two predictor variables. Perform an LM, plot the results, and state if this changes your interpretation of the relationship between variables (10 pts)
 > lm(formula = carapace_length ~ carapace_width, data = crab)

 > ggplot(crab, aes(x = carapace_length, y = carapace_width, color = sex)) + geom_point()

 This does not change my interpretation of the relationship between the variables.

Part Three
Add and commit this document (5 pts)
#Commands here

Push your changes to github (10 pts)
#Commands here

MS students
My expectation is that you’ll do this with your own data. If any part of this doesn’t make sense with your data, please get in touch ASAP so we can work it out.